name: Run Bot

on:
  workflow_dispatch:        # Əl ilə işə salmaq üçün
  schedule:
    - cron: "0 9,14,20 * * *"   # Hər gün saat 09:00, 14:00 və 20:00-da

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python main.py
