name: Run Bot

on:
  workflow_dispatch:      # əl ilə işə salmaq üçün
  schedule:
    - cron: '0 9,14,20 * * *'   # gündə 3 dəfə (UTC)

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests feedparser beautifulsoup4 html2text

      # ---- TELEGRAM birbaşa ping testi (token/chat_id doğru-dursa 200 qaytaracaq) ----
      - name: TG direct test (curl)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          set -x
          curl -sS "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="Ping from GitHub Actions ✅" | head -c 400

      # ---- Minimal ayrıca ping.py (logda status+body görünsün) ----
      - name: Minimal TG ping
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python .github/workflows/ping.py

      # ---- Əsas bot ----
      - name: Run script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
          ACTIVE_PLATFORMS:   ${{ secrets.ACTIVE_PLATFORMS }}
          KEYWORDS:           ${{ secrets.KEYWORDS }}
          DAILY_LIMIT:        ${{ secrets.DAILY_LIMIT }}
        run: python .github/workflows/main.py
